### ISSUE TITLE
`install` task is not up to date with `tags` model

### ISSUE THREAD

**Issue by jeanparpaillon** [tableturn/dymo#28]
`install` task creates migration file for `tags` table.
The migration is missing `assignable` column.

`create_tags` migration is up-to-date but is not used by `install` task.

For the sake of consistence, test should use same migration definition as the mix task.

**Comment by hickscorp** [comment]
@jeanparpaillon I think this was fixed. Can you confirm, if you have the chance please?

**Comment by jeanparpaillon** [comment]
Looks good to me
https://github.com/tableturn/dymo/commit/99a5bbd88381d6cd8b92641bbdff76bd1b885be1
