### ISSUE TITLE
The '@spec' of Dymo.Tag.find_exising/1 doesn't match it's real output

### ISSUE THREAD

**Issue by GuillemAcero** [tableturn/dymo#29]
The '@spec' of  `Dymo.Tag.find_exising/1` states that the function should return a type `label_or_lables`. 

This type could be a `label` (that could be at the same time: `String.t() | {Ns.t(), String.t()}`) or a list of labels: `[labels]`

`find_existing/1 `(after all the patter-matches) returns `%Dymo.Tag{}` struct or `nil`. This doesn't match whit the spec explained before

**Comment by hickscorp** [comment]
This should have been fixed by https://github.com/tableturn/dymo/commit/470db35bc2a83fca49c0f3cf3c3d9e03c4d1ec0b .

**Comment by hickscorp** [comment]
@GuillemAcero any update on this? I'll close for now.
